const personListLong = [
  {
    phone_no: "01766924290",
    designation_name: "Professor",
    father_Name: "Late Md. Abubaker Master",
    official_ID: "T200531014",
    current_Designation_ID: "A0006",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1968-09-06 00:00:00.0",
    system_ID: "00307",
    sex: "M",
    increment_Heldup: "0",
    marital_Status: "Married",
    email_Address: "liakot@iict.buet.ac.bd",
    account_No: "34184464",
    religion: "Islam",
    thana: "Alamdanga",
    mother_Name: "Mrs. Shaharunnesa",
    district: "Chuadanga",
    name: "Dr. Md. Liakot Ali",
    current_Join_Date: "03/07/2011",
    blood_Group: "AB+ ve",
    village: "Village + P.O. Khashkarara",
    present_Address: "30/4-A, Teachers  Quarter, BUET, Dhaka-1000",
  },
  {
    designation_name: "Professor",
    father_Name: "Md. Mozammel Hossain",
    official_ID: "T198231001",
    current_Designation_ID: "A0006",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1959-06-28 00:00:00.0",
    system_ID: "20223",
    sex: "M",
    increment_Heldup: "0",
    marital_Status: "Married",
    email_Address: "lutfulkabir@iict.buet.ac.bd",
    account_No: "33001595",
    religion: "Islam",
    thana: "Santhia",
    mother_Name: "Latifa Hossain",
    district: "Pabna",
    name: "Dr. S.M. Lutful Kabir",
    current_Join_Date: "10/07/1996",
    blood_Group: "B+ ve",
    village: "Village  Porat,  Santhia",
    present_Address: "4/E,  BUET Teachers  Quarter, BUET, Dhaka",
  },
  {
    phone_no: "01552015527",
    designation_name: "Professor",
    father_Name: "Mr. Md. Yeahhyea",
    official_ID: "T200331004",
    current_Designation_ID: "A0006",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1965-02-21 00:00:00.0",
    system_ID: "00598",
    sex: "M",
    increment_Heldup: "0",
    marital_Status: "Married",
    email_Address: "mdsaifulislam@iict.buet.ac.bd",
    account_No: "34185611",
    religion: "Islam",
    thana: "Pirgonj",
    mother_Name: "Mrs.Jahanara Begum",
    district: "Thakurgaon",
    name: "Dr. Md. Saiful Islam",
    current_Join_Date: "23/11/2010",
    blood_Group: "B+ ve",
    village: "RDRS Road, Pirgonj Pourashova, P.O. Pirgonj",
    present_Address: "30/2-B, Teachers  Quater, BUET",
  },
  {
    designation_name: "Professor",
    father_Name: "Professor K.A.M. Shahadat Hossain Mondal",
    official_ID: "T200531013",
    current_Designation_ID: "A0006",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1980-10-14 00:00:00.0",
    system_ID: "00302",
    sex: "M",
    increment_Heldup: "0",
    marital_Status: "Married",
    email_Address: "rubaiyat97@iict.buet.ac.bd",
    account_No: "34145978",
    religion: "Islam",
    thana: "Boalia",
    against_designation_ID: "A0010",
    mother_Name: "Mrs. U.M. Rahela Khatoon",
    district: "Rajshahi",
    name: "Dr. Md. Rubaiyat Hossain Mondal",
    current_Join_Date: "24/12/2018",
    blood_Group: "B+ ve",
    village: "102/102 Talaimari, Raninagar, P.O. Kazla",
    present_Address: "48/2-G, Teachers  Quarter, BUET, Dhaka-1000",
  },
  {
    designation_name: "Associate Professor",
    father_Name: "Mohammed Nurul Mustafa ",
    official_ID: "T201531026",
    current_Designation_ID: "A0010",
    department_ID: "000107",
    employment_Status: "Probation",
    date_of_birth: "1981-01-12 00:00:00.0",
    system_ID: "22289",
    sex: "M",
    marital_Status: "Married",
    account_No: "01028616",
    thana: "Kotwail",
    mother_Name: "Jahanara Mahbuba Hasnat ",
    district: "chittagong",
    name: "Dr. Hossen Asiful Mustafa",
    current_Join_Date: "05/09/2020",
    present_Address: "House -3, Road- 29",
  },
  {
    designation_name: "Assistant Professor",
    father_Name: "Md. Shamsul Haque",
    official_ID: "T202231029",
    current_Designation_ID: "A0012",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1987-01-01 00:00:00.0",
    system_ID: "22938",
    sex: "M",
    marital_Status: "Single",
    account_No: "01037525",
    religion: "Islam",
    thana: "Rangpur Sadar",
    mother_Name: "Mst. Jarina Begum",
    district: "Rangpur",
    name: "Dr. Md. Jarez Miah",
    current_Join_Date: "05/01/2022",
    present_Address: "Village- Fakiran, Post Office- Haridevpur",
  },
  {
    phone_no: "01521201725",
    designation_name: "Assistant Professor",
    father_Name: "Mohammad Hassan Mansur",
    official_ID: "T202031028",
    current_Designation_ID: "A0012",
    department_ID: "000107",
    employment_Status: "Probation",
    date_of_birth: "1997-11-08 00:00:00.0",
    system_ID: "22783",
    sex: "M",
    marital_Status: "Married",
    account_No: "01029059",
    religion: "Islam",
    thana: "Tongibari",
    mother_Name: "Mariam Begum ",
    district: "Munshigonj",
    name: "Mohammad Muntasir Hassan ",
    current_Join_Date: "20/07/2022",
    present_Address: "15, Kakrail ",
  },
  {
    designation_name: "Assistant Professor",
    father_Name: "Mr. A.K.M. Asaduzzaman",
    official_ID: "T201431025",
    current_Designation_ID: "A0012",
    department_ID: "000107",
    employment_Status: "Probation",
    date_of_birth: "1985-12-06 00:00:00.0",
    system_ID: "22083",
    sex: "M",
    marital_Status: "Married",
    account_No: "34189785",
    religion: "Islam",
    thana: "Rajpara",
    mother_Name: "Mrs. Rozy Zaman",
    district: "Rajshahi-6000",
    name: "Mr. Mohammad Imam Hasan Bin Asad",
    current_Join_Date: "31/07/2016",
    present_Address: "House No. 497, Road No. 15, D.O.H.S, Mirpur, Dhaka",
  },
  {
    designation_name: "Lecturer",
    father_Name: "Mr. Md. Nazrul Islam",
    official_ID: "T201131022",
    current_Designation_ID: "A0013",
    department_ID: "000107",
    employment_Status: "Temporary",
    date_of_birth: "1988-11-13 00:00:00.0",
    system_ID: "21733",
    sex: "M",
    increment_Heldup: "0",
    marital_Status: "Married",
    account_No: "34229459",
    religion: "Islam",
    thana: "Kalabagan",
    mother_Name: "Mrs. Afroza Begum",
    district: "Dhaka",
    name: "Miss Nazifah Islam",
    current_Join_Date: "23/03/2011",
    present_Address: "Flat no A4, Ena Endear, 93 Bashiruddin Road, ",
  },
  {
    designation_name: "Lecturer",
    father_Name: "Dr. S.M. Nazrul Islam",
    official_ID: "T201031021",
    current_Designation_ID: "A0013",
    department_ID: "000107",
    employment_Status: "Ad-hoc",
    date_of_birth: "1986-06-26 00:00:00.0",
    system_ID: "21692",
    sex: "M",
    increment_Heldup: "0",
    marital_Status: "Single",
    email_Address: "naeem@iict.buet.ac.bd",
    account_No: "34205328",
    religion: "Islam",
    mother_Name: "Mrs. Mahmuda Khatun",
    name: "Mr. S.M. Naeemul Islam",
    current_Join_Date: "26/10/2010",
    present_Address: "48/7B BUET Teachers Quarter, BUET, Dhaka",
  },
  {
    designation_name: "Lecturer",
    father_Name: "Md Abdur Rahman",
    official_ID: "T202331030",
    current_Designation_ID: "A0013",
    department_ID: "000107",
    employment_Status: "Temporary",
    date_of_birth: "1997-12-28 00:00:00.0",
    system_ID: "23097",
    sex: "M",
    marital_Status: "Single",
    email_Address: "saminrk@iict.buet.ac.bd",
    religion: "Islam",
    thana: "Dakshinkhan",
    mother_Name: "Mst. Anjumanara",
    district: "Dhaka",
    name: "Samin Rahman Khan",
    current_Join_Date: "30/04/2023",
    blood_Group: "A+",
    present_Address: "149/3, Holan, Dakshinkhan, Dhaka-1230",
  },
  {
    designation_name: "Senior Programmer",
    father_Name: "Mr. Shahidullah Patwary",
    official_ID: "O200831024",
    current_Designation_ID: "Bo5oo17",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1971-06-10 00:00:00.0",
    system_ID: "20662",
    sex: "M",
    increment_Heldup: "0",
    marital_Status: "Married",
    email_Address: "mdelwar@iict.buet.ac.bd",
    account_No: "34239854",
    religion: "Islam",
    mother_Name: "Mrs. Momtaz Begum",
    name: "Mr. Mohammad Delwar Hossain",
    current_Join_Date: "30/11/2008",
    village: "204-205 Phatantory Road, Nazirport Doublemooring, Chittagong",
    present_Address: "52/204, Officers Quarter, BUET, Dhaka-1000",
  },
  {
    designation_name: "Senior System Administrator",
    father_Name: "Md. Tauaidul Alam Chowdhory ",
    official_ID: "O201631037",
    current_Designation_ID: "Bo5oo18c1",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1980-11-21 00:00:00.0",
    system_ID: "22457",
    sex: "M",
    marital_Status: "Married",
    account_No: "01000329",
    religion: "Islam",
    thana: "Pallobi",
    against_designation_ID: "Bo5oo18",
    district: "Dhaka",
    name: "Sazzad Wahid",
    current_Join_Date: "02/04/2020",
    present_Address: "House# 4, Road 7/2, Block-B, Mirpur-12-B",
  },
  {
    designation_name: "Senior System Analyst",
    father_Name: "Mr. Birendra Nath Sana",
    official_ID: "O200931025",
    current_Designation_ID: "Bo5oo19c1",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1983-11-01 00:00:00.0",
    system_ID: "20669",
    sex: "M",
    increment_Heldup: "0",
    marital_Status: "Single",
    email_Address: "joydebsana@iict.buet.ac.bd",
    account_No: "34246479",
    religion: "Hindu",
    thana: "Asasuni",
    against_designation_ID: "Bo6oo04",
    mother_Name: "Mrs. Parboty Rani Sana",
    district: "Satkhira",
    name: "Mr. Joydeb Kumar Sana",
    current_Join_Date: "03/01/2020",
    village:
      "Village: Mohiskur,   P.O.: Puijala, Thana : Asasuni,   Dist.:   Satkhira",
    present_Address: "C/o IICT Office, BUET, Dhaka-1000",
  },
  {
    designation_name: "Programmer",
    father_Name: "Mir Abu Taher",
    official_ID: "O201431038",
    current_Designation_ID: "Bo6oo04",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1981-01-01 00:00:00.0",
    system_ID: "22201",
    sex: "M",
    marital_Status: "Married",
    email_Address: "toraf@iict.buet.ac.bd",
    account_No: "01027008",
    religion: "Islam",
    thana: "Sadar",
    against_designation_ID: "Bo9o601c2",
    mother_Name: "Kazi Ferdoushi Ara",
    district: "Mymensingh",
    name: "Mir Abu Toraf",
    current_Join_Date: "27/08/2019",
    present_Address: "50, BC Das Street ( 2nd  Flor)",
  },
  {
    designation_name: "Senior Instrument Engineer",
    father_Name: "Mr. Md. Sabed Ali Akanda",
    official_ID: "O198931007",
    current_Designation_ID: "Bo6oo06",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1961-01-01 00:00:00.0",
    system_ID: "20519",
    sex: "M",
    increment_Heldup: "0",
    marital_Status: "Married",
    account_No: "34012955",
    religion: "Islam",
    thana: "Gobindaganj",
    mother_Name: "Mrs.Rejia Begum",
    district: "Gaibandha",
    name: "Mr. Md. Rezaul Hoque Akanda",
    current_Join_Date: "16/10/2003",
    village:
      "Village Satail Batail, P.O. Gobindaganj, Thana:   Gobindaganj,    District:  Gaibandha",
    present_Address: "53/7, BUET Officers? Qurter, BUET, Dhaka-1000",
  },
  {
    designation_name: "Assistant Programmer",
    father_Name: "Mr. Mir Amjad Ali",
    official_ID: "O200231015",
    current_Designation_ID: "Bo9o601c2",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1977-12-05 00:00:00.0",
    system_ID: "20602",
    sex: "M",
    increment_Heldup: "0",
    marital_Status: "Married",
    account_No: "34178573",
    religion: "Islam",
    thana: "Mirpur",
    against_designation_ID: "Bo9o601",
    mother_Name: "Mrs.",
    district: "Dhaka",
    name: "Mr.  Mir Mohammad Abu Sayem",
    current_Join_Date: "03/01/2009",
    village: "Section 13, Block B, Lane 9, House 2, Mirpur, Dhaka",
    present_Address: "Section 13, Block B, Lane 9, House 2",
  },
  {
    designation_name: "Assistant Programmer",
    father_Name: "Mr. Md. Hafiz Ahmed",
    official_ID: "O200231014",
    current_Designation_ID: "Bo9o601c2",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1982-01-25 00:00:00.0",
    system_ID: "20601",
    sex: "M",
    increment_Heldup: "0",
    marital_Status: "Single",
    account_No: "34178747",
    religion: "Islam",
    thana: "Babuganj",
    mother_Name: "Mrs. Sufia Khatun",
    district: "Barisal",
    name: "Mr. Md. Mahbub Kabir",
    current_Join_Date: "05/10/2013",
    village:
      "Village East Bhuturdia, P.O. Bhuturdia Thana:   Babuganj     District:  :  Barisal",
    present_Address: "M.Sc. Student, Royal Institute of Technology, Sweden",
  },
  {
    designation_name: "Maintenance Engineer",
    father_Name: "Mir Ahmed Bhuiyan",
    official_ID: "O201531034",
    current_Designation_ID: "Bo9o704c2",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1987-12-28 00:00:00.0",
    system_ID: "22339",
    sex: "M",
    marital_Status: "Single",
    account_No: "01028569",
    religion: "Islam",
    thana: "Nagalkot",
    against_designation_ID: "Bo9o704c1",
    mother_Name: "Rahima Khatun",
    district: "Comilla",
    name: "Nasir Ahmed Bhuiyan",
    current_Join_Date: "01/07/2020",
    present_Address: "Flat# 5/B, House# Ga-32/2, Shahjadpur",
  },
  {
    designation_name: "Maintenance Engineer",
    father_Name: "Mr. Mohammad Zahurul Islam",
    official_ID: "O200531019",
    current_Designation_ID: "Bo9o704c2",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1977-09-09 00:00:00.0",
    system_ID: "20623",
    sex: "M",
    increment_Heldup: "0",
    marital_Status: "Married",
    account_No: "34219162",
    religion: "Islam",
    thana: "Palash",
    against_designation_ID: "Bo9o704",
    mother_Name: "Mrs.Nurunnahar Begum",
    district: "Narshingdi",
    name: "Mr. Mohammad Salekul Islam",
    current_Join_Date: "09/11/2005",
    village:
      "Village + P.O. Santanpara, Thana: Palash       District:  Narshingdi",
    present_Address: "311/2, Shah Ali Bag Road, Mirpur-1, Dhaka",
  },
  {
    designation_name: "Internet Service Officer",
    father_Name: "Mr. Sushil Kumar Samadder",
    official_ID: "O201331030",
    current_Designation_ID: "C10o901c1",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1985-11-10 00:00:00.0",
    system_ID: "22024",
    sex: "M",
    marital_Status: "Single",
    account_No: "34292606",
    religion: "Hindu",
    thana: "Boalmari",
    mother_Name: "Mrs. Bithika Rani Samadder",
    district: "Faridpur",
    name: "Mr. Pabitra Samadder",
    current_Join_Date: "05/10/2013",
    present_Address: "237/2, 3rd Floor, East Nakhal Para, Tejgoan, Dhaka-1215",
  },
  {
    designation_name: "Internet Service Officer",
    father_Name: "Hazi Md Syed Ali",
    official_ID: "O201431033",
    current_Designation_ID: "C10o901c1",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1990-02-22 00:00:00.0",
    system_ID: "22207",
    sex: "M",
    marital_Status: "Single",
    account_No: "01027020",
    religion: "Islam",
    thana: "Motihar",
    mother_Name: "Mst. Satara Begum",
    district: "Rajshahi-6206",
    name: "Mr. Md. Habibur Rahman",
    current_Join_Date: "27/08/2014",
    blood_Group: "B+ve",
    present_Address:
      "10/A, Globe Nebash, (7th floor-D), Shegunbagecha, Dhaka-1000",
  },
  {
    designation_name: "Assistant Technical Officer",
    father_Name: "Mr. Md. Abu Taher",
    official_ID: "O200631022",
    current_Designation_ID: "D10oo0601",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1979-07-06 00:00:00.0",
    system_ID: "20637",
    sex: "M",
    increment_Heldup: "0",
    marital_Status: "Married",
    account_No: "34223081",
    religion: "Islam",
    thana: "Sadar Kakhin",
    mother_Name: "Mrs. Morium Begum",
    district: "Comilla",
    name: "Mr. Md. Khorshed Alam",
    current_Join_Date: "01/07/2006",
    village:
      "Village South Bagmara, P.O. Kotbari Thana:  Kotwali     District:  Comilla",
    present_Address:
      "C/o Md. Shah Alam, Rank USM, CS no.523640, Group CSTC, COD Dhaka Cantonment, Dhaka-1206",
  },
  {
    designation_name: "AC Mechanic",
    father_Name: "Mr. Mukunda Lal Singh",
    official_ID: "K198631001",
    current_Designation_ID: "E15oo01",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1964-09-03 00:00:00.0",
    system_ID: "20790",
    sex: "M",
    increment_Heldup: "0",
    marital_Status: "Married",
    account_No: "34036252",
    religion: "Islam",
    mother_Name: "Mrs.",
    name: "Mr. Dayamay Singh",
    current_Join_Date: "23/04/1993",
    village:
      "Village  Bhanga Bhita,  P.O. Masail, Thana  Nababgonj,   Dist. Dhaka",
    present_Address: "14/F-A, Staff Quarter,  BUET, Dhaka-1000",
  },
  {
    designation_name: "OMR and Print Operator",
    father_Name: "Mr. Anower Hossain",
    official_ID: "K202131016",
    current_Designation_ID: "E15oo12",
    department_ID: "000107",
    employment_Status: "Probation",
    date_of_birth: "1990-12-09 00:00:00.0",
    system_ID: "22098",
    sex: "M",
    marital_Status: "Married",
    account_No: "34294206",
    religion: "Islam",
    thana: "Shibalaya",
    mother_Name: "Mrs. Nurzahan Begum",
    district: "Manikgonj",
    name: "Mr. Md. Eshaque Ali",
    current_Join_Date: "10/11/2021",
    blood_Group: "A+ve",
    present_Address:
      "Electrical and Electronic Engineering Department, BUET, Dhaka",
  },
  {
    designation_name: "Driver",
    father_Name: "Md. Nurul Islam Dhali",
    official_ID: "K202131015",
    current_Designation_ID: "E16oo07",
    department_ID: "000107",
    employment_Status: "Probation",
    date_of_birth: "1983-12-08 00:00:00.0",
    system_ID: "22916",
    sex: "M",
    marital_Status: "Married",
    account_No: "01037229",
    religion: "Islam",
    thana: "Munshigonj",
    mother_Name: "Ms. Bina Akhtar",
    district: "Munshigonj",
    name: "Md. Mahbub Rahman Rana",
    current_Join_Date: "07/11/2021",
    present_Address: "38/5 BC Das Steet ",
  },
  {
    designation_name: "AC-cum-Generator Technician",
    father_Name: "Md. Zahir Uddin",
    official_ID: "K201531011",
    current_Designation_ID: "E200008",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1991-09-10 00:00:00.0",
    system_ID: "22374",
    sex: "M",
    marital_Status: "Single",
    account_No: "01028984",
    religion: "Islam",
    thana: "Raipura",
    mother_Name: "Jolekha  Begum",
    district: "Narsingdi",
    name: "Md. Shohag Mia",
    current_Join_Date: "15/12/2015",
    present_Address: "Vill:  Batiara , P.O: Kataghat Bazar",
  },
  {
    designation_name: "Assistant Internet Service Officer",
    father_Name: "Md. Nurul Amin",
    official_ID: "O202231039",
    current_Designation_ID: "E200030",
    department_ID: "000107",
    employment_Status: "Probation",
    date_of_birth: "1993-01-01 00:00:00.0",
    system_ID: "22940",
    sex: "M",
    marital_Status: "Married",
    account_No: "01029685",
    religion: "Islam",
    thana: "Shakhipur",
    mother_Name: "Shafali Begum ",
    district: "Shariatpur",
    name: "Md. Yeer Sharif",
    current_Join_Date: "05/01/2022",
    present_Address: "Kallyanpur",
  },
  {
    designation_name: "Senior Assistant Registrar",
    father_Name: "Mr.  Akkas Howlader",
    official_ID: "O201331032",
    current_Designation_ID: "E200054",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1971-12-25 00:00:00.0",
    system_ID: "21000",
    sex: "M",
    increment_Heldup: "0",
    marital_Status: "Married",
    account_No: "34146588",
    religion: "Islam",
    thana: " Tongibari",
    against_designation_ID: "Bo9oo02",
    mother_Name: "Mrs.Abala Khatun ",
    district: "Munshigonj",
    name: "Mr. Alamgir Hossain Howlader",
    current_Join_Date: "02/05/2021",
    village:
      "Village  Hazinoadda,  P.O. Banari, Thana  Tongibari,  Dist. Munshigonj",
    present_Address: "101/2, Katasur, 1st Floor, Sherebangla nagar,Dhaka-1207",
  },
  {
    designation_name: "Senior Internet Service Officer",
    father_Name: "Mr. Mohammed Goni Miah",
    official_ID: "O200931026",
    current_Designation_ID: "E200075",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1978-04-02 00:00:00.0",
    system_ID: "20670",
    sex: "M",
    increment_Heldup: "0",
    marital_Status: "Married",
    account_No: "34246561",
    religion: "Islam",
    thana: "Barcharampur",
    against_designation_ID: "C10o901",
    mother_Name: "Mrs. Rekha Begum",
    district: "B Baria",
    name: "Mr. Mohammad Babul Miah",
    current_Join_Date: "01/07/2012",
    village:
      "Village:  Asad Nagar,   P.O.: Banchharanpur,  Thana :    Barchharampur,       Dist.:   B Baria",
    present_Address: "C/o IICT Office,  BUET, Dhaka-1000",
  },
  {
    designation_name: "Senior Technical Officer",
    father_Name: "Mr. Md. Islam Hossain",
    official_ID: "O200631020",
    current_Designation_ID: "E200129",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1978-03-01 00:00:00.0",
    system_ID: "20635",
    sex: "M",
    increment_Heldup: "0",
    marital_Status: "Married",
    account_No: "34223008",
    religion: "Islam",
    thana: "Nawabgonj Sadar",
    against_designation_ID: "D10oo0601",
    mother_Name: "Mrs. Rahima Begum",
    district: "Chapai Nawabgonj",
    name: "Mr. Md. Mukhtaruzzaman",
    current_Join_Date: "01/07/2019",
    village:
      "Village: Baliadanga,   P.O.: Baliadanga, Thana : Nawabgonj Sadar,        Dist.:   Chapai Nawabgonj",
    present_Address: "IICT Office, BUET, Dhaka-1000",
  },
  {
    designation_name: "Senior Technical Officer",
    father_Name: "Late Khandakar Nazrul Islam",
    official_ID: "O200631023",
    current_Designation_ID: "E200129",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1978-08-02 00:00:00.0",
    system_ID: "20638",
    sex: "M",
    increment_Heldup: "0",
    marital_Status: "Married",
    account_No: "34223271",
    religion: "Islam",
    thana: "Shailakupa",
    against_designation_ID: "D10oo0601",
    mother_Name: "Mrs. Nurjahan Begum",
    district: "Jhinaidah",
    name: "Mr. Khandakar Al Mamun",
    current_Join_Date: "10/07/2019",
    village:
      "Vill Madhapada, P.O. Shailakupa Thana:   Shailakupa    District:  Jhinaidah",
    present_Address:
      "5th Floor, H-37, E-Block, Lalmatia, Mohammadpur, Dhaka-1207",
  },
  {
    designation_name: "Senior Technical Officer",
    father_Name: "Late Md. Nazir Ahmmed Miazi",
    official_ID: "O200631021",
    current_Designation_ID: "E200129",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1982-06-02 00:00:00.0",
    system_ID: "20636",
    sex: "M",
    increment_Heldup: "0",
    marital_Status: "Married",
    account_No: "34223503",
    religion: "Islam",
    thana: "Fulgazi",
    against_designation_ID: "D10oo0601",
    mother_Name: "Mrs. Jarina Khatun",
    district: "Feni",
    name: "Mr. Mohammed Shofi Ullah Miazi",
    current_Join_Date: "26/07/2019",
    village:
      "Vill North Anandapur, P.O. Munshirhat Thana: Fulgazi      District:  Feni",
    present_Address: "House no 03, Road no 11, Nikunja-2, Khilkhet, Dhaka",
  },
  {
    designation_name: "Senior Technical Officer SGS",
    father_Name: "Mr. Md. Abdul Gafur",
    official_ID: "O199831031",
    current_Designation_ID: "E200131",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1963-09-30 00:00:00.0",
    system_ID: "20792",
    sex: "M",
    increment_Heldup: "0",
    marital_Status: "Married",
    account_No: "34036269",
    religion: "Islam",
    thana: "Kotwali",
    against_designation_ID: "E15oo12",
    mother_Name: "Mrs.",
    district: "Comilla",
    name: "Mr .Md.Tazul Islam",
    current_Join_Date: "29/04/2009",
    village: "Village Banasua,  P.O. Banasua,   Thana  Kotwali, Dist. Comilla",
    present_Address: "10/E,   Staff Quarter, BUET, Dhaka-1000",
  },
  {
    designation_name: "Library Assistant-cum-Documentation Assistant",
    father_Name: "Late Mohammad Suroj Miah",
    official_ID: "K200931017",
    current_Designation_ID: "E200152",
    department_ID: "000107",
    employment_Status: "Probation",
    date_of_birth: "1989-01-18 00:00:00.0",
    system_ID: "21887",
    sex: "M",
    marital_Status: "Single",
    account_No: "34253574",
    religion: "Islam",
    thana: "Araihazar",
    mother_Name: "Late Momela Begum",
    district: "Narayangonj",
    name: "Mohammad. Abu Hanif",
    current_Join_Date: "24/10/2021",
    present_Address: "Vill: Khangkanda(s) Nayanpara, P.O: Naynabad",
  },
  {
    designation_name: "Lab. Attendant",
    father_Name: "Md. Zakir Hossain",
    official_ID: "K202031014",
    current_Designation_ID: "H191601c1",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1994-06-26 00:00:00.0",
    system_ID: "22775",
    sex: "M",
    marital_Status: "Married",
    account_No: "01036033",
    religion: "Islam",
    thana: "Meghna",
    mother_Name: "Kamrun Nahar",
    district: "Cumilla",
    name: "Zahidul Islam",
    current_Join_Date: "14/03/2020",
    present_Address: "64/7E, BUET Staff Quarter",
  },
  {
    designation_name: "Senior Lab Attendant",
    father_Name: "Late Abdul Majid Sarker",
    official_ID: "K200531013",
    current_Designation_ID: "H191601c2",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1978-09-15 00:00:00.0",
    system_ID: "21435",
    sex: "M",
    increment_Heldup: "0",
    marital_Status: "Married",
    account_No: "34202424",
    religion: "Islam",
    thana: "Rajarhat",
    against_designation_ID: "H191601c1",
    mother_Name: "Mrs. Hasen Banu",
    district: "Kurigram",
    name: "Mr. Ariful Islam Sarker",
    current_Join_Date: "11/04/2011",
    village:
      "Village Taluk Shubal, P.O. Jarshoyahat,  Thana  Rajarhat, Dist. Kurigram",
    present_Address: "44/20-Gha,  BUET, Dhaka-1000",
  },
  {
    designation_name: "Senior Lab Attendant Gr. 2",
    father_Name: "Md. Jhurul Haque",
    official_ID: "K201331012",
    current_Designation_ID: "H191601c3",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1992-04-03 00:00:00.0",
    system_ID: "22025",
    sex: "M",
    marital_Status: "Single",
    account_No: "34290824",
    religion: "Islam",
    against_designation_ID: "H191601c1",
    name: "Md. Nur Amin",
    current_Join_Date: "03/07/2018",
  },
  {
    designation_name: "Office Attendant",
    father_Name: "Late Joynuddin Howlader",
    official_ID: "M200131002",
    current_Designation_ID: "I19oo13",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1982-01-01 00:00:00.0",
    system_ID: "21382",
    sex: "M",
    increment_Heldup: "0",
    marital_Status: "Married",
    account_No: "34165423",
    religion: "Islam",
    thana: "Nalchithi",
    against_designation_ID: "I20oo08",
    mother_Name: "Mrs. Suratun Ness",
    district: "Jhalokathi",
    name: "Mr. Md. Khorshed Alam",
    current_Join_Date: "17/01/2006",
    village:
      "Village  Boichaudi, P.O. Nalchithi,  Thana  Nalchithi,  Dist. Jhalokathi",
    present_Address: "Water Pump Azad Quarter, BUET, Dhaka-1000",
  },
  {
    designation_name: "Senior Office Attendant",
    father_Name: "Late Tajul Islam",
    official_ID: "M200131003",
    current_Designation_ID: "I19oo1301",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1981-01-01 00:00:00.0",
    system_ID: "21383",
    sex: "M",
    increment_Heldup: "0",
    marital_Status: "Married",
    account_No: "34172849",
    religion: "Islam",
    thana: "Laksam",
    mother_Name: "Mrs. Aklima Akter",
    district: "Comilla",
    name: "Mr. Md. Abdul Aziz",
    current_Join_Date: "30/09/2006",
    village:
      "Village  Uttar Fenua,  P.O. Uttar Howla, Thana  Laksam,   Dist. Comilla",
    present_Address: "44/20-Ka, BUET, Dhaka-1000",
  },
  {
    designation_name: "Section Officer",
    father_Name: "Late Qazi Abdul Quader",
    official_ID: "O199631016",
    current_Designation_ID: "U0001",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1951-03-01 00:00:00.0",
    system_ID: "20553",
    sex: "M",
    increment_Heldup: "0",
    marital_Status: "Married",
    account_No: "34015272",
    religion: "Islam",
    thana: "Laksam",
    against_designation_ID: "D10oo01",
    mother_Name: "Late Jarina Khatun",
    district: "Comilla",
    name: "Mr. Md. Abu Taher",
    current_Join_Date: "05/05/1996",
    village:
      "Village Thengarbam, P.O. Kashipur Madrasha, Thana:  Laksam     District:  Comilla",
    present_Address: "13/Q, BUET Officers Quarter, BUET, Dhaka",
  },
];
const personListShort = [
  {
    phone_no: "01766924290",
    designation_name: "Professor",
    father_Name: "Late Md. Abubaker Master",
    official_ID: "T200531014",
    current_Designation_ID: "A0006",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1968-09-06 00:00:00.0",
    system_ID: "00307",
    sex: "M",
    increment_Heldup: "0",
    marital_Status: "Married",
    email_Address: "liakot@iict.buet.ac.bd",
    account_No: "34184464",
    religion: "Islam",
    thana: "Alamdanga",
    mother_Name: "Mrs. Shaharunnesa",
    district: "Chuadanga",
    name: "Dr. Md. Liakot Ali",
    current_Join_Date: "03/07/2011",
    blood_Group: "AB+ ve",
    village: "Village + P.O. Khashkarara",
    present_Address: "30/4-A, Teachers  Quarter, BUET, Dhaka-1000",
  },
  {
    designation_name: "Professor",
    father_Name: "Md. Mozammel Hossain",
    official_ID: "T198231001",
    current_Designation_ID: "A0006",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1959-06-28 00:00:00.0",
    system_ID: "20223",
    sex: "M",
    increment_Heldup: "0",
    marital_Status: "Married",
    email_Address: "lutfulkabir@iict.buet.ac.bd",
    account_No: "33001595",
    religion: "Islam",
    thana: "Santhia",
    mother_Name: "Latifa Hossain",
    district: "Pabna",
    name: "Dr. S.M. Lutful Kabir",
    current_Join_Date: "10/07/1996",
    blood_Group: "B+ ve",
    village: "Village  Porat,  Santhia",
    present_Address: "4/E,  BUET Teachers  Quarter, BUET, Dhaka",
  },
  {
    phone_no: "01552015527",
    designation_name: "Professor",
    father_Name: "Mr. Md. Yeahhyea",
    official_ID: "T200331004",
    current_Designation_ID: "A0006",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1965-02-21 00:00:00.0",
    system_ID: "00598",
    sex: "M",
    increment_Heldup: "0",
    marital_Status: "Married",
    email_Address: "mdsaifulislam@iict.buet.ac.bd",
    account_No: "34185611",
    religion: "Islam",
    thana: "Pirgonj",
    mother_Name: "Mrs.Jahanara Begum",
    district: "Thakurgaon",
    name: "Dr. Md. Saiful Islam",
    current_Join_Date: "23/11/2010",
    blood_Group: "B+ ve",
    village: "RDRS Road, Pirgonj Pourashova, P.O. Pirgonj",
    present_Address: "30/2-B, Teachers  Quater, BUET",
  },
  {
    designation_name: "Professor",
    father_Name: "Professor K.A.M. Shahadat Hossain Mondal",
    official_ID: "T200531013",
    current_Designation_ID: "A0006",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1980-10-14 00:00:00.0",
    system_ID: "00302",
    sex: "M",
    increment_Heldup: "0",
    marital_Status: "Married",
    email_Address: "rubaiyat97@iict.buet.ac.bd",
    account_No: "34145978",
    religion: "Islam",
    thana: "Boalia",
    against_designation_ID: "A0010",
    mother_Name: "Mrs. U.M. Rahela Khatoon",
    district: "Rajshahi",
    name: "Dr. Md. Rubaiyat Hossain Mondal",
    current_Join_Date: "24/12/2018",
    blood_Group: "B+ ve",
    village: "102/102 Talaimari, Raninagar, P.O. Kazla",
    present_Address: "48/2-G, Teachers  Quarter, BUET, Dhaka-1000",
  },
  {
    designation_name: "Associate Professor",
    father_Name: "Mohammed Nurul Mustafa ",
    official_ID: "T201531026",
    current_Designation_ID: "A0010",
    department_ID: "000107",
    employment_Status: "Probation",
    date_of_birth: "1981-01-12 00:00:00.0",
    system_ID: "22289",
    sex: "M",
    marital_Status: "Married",
    account_No: "01028616",
    thana: "Kotwail",
    mother_Name: "Jahanara Mahbuba Hasnat ",
    district: "chittagong",
    name: "Dr. Hossen Asiful Mustafa",
    current_Join_Date: "05/09/2020",
    present_Address: "House -3, Road- 29",
  },
  {
    designation_name: "Assistant Professor",
    father_Name: "Md. Shamsul Haque",
    official_ID: "T202231029",
    current_Designation_ID: "A0012",
    department_ID: "000107",
    employment_Status: "Permanent",
    date_of_birth: "1987-01-01 00:00:00.0",
    system_ID: "22938",
    sex: "M",
    marital_Status: "Single",
    account_No: "01037525",
    religion: "Islam",
    thana: "Rangpur Sadar",
    mother_Name: "Mst. Jarina Begum",
    district: "Rangpur",
    name: "Dr. Md. Jarez Miah",
    current_Join_Date: "05/01/2022",
    present_Address: "Village- Fakiran, Post Office- Haridevpur",
  },
  {
    phone_no: "01521201725",
    designation_name: "Assistant Professor",
    father_Name: "Mohammad Hassan Mansur",
    official_ID: "T202031028",
    current_Designation_ID: "A0012",
    department_ID: "000107",
    employment_Status: "Probation",
    date_of_birth: "1997-11-08 00:00:00.0",
    system_ID: "22783",
    sex: "M",
    marital_Status: "Married",
    account_No: "01029059",
    religion: "Islam",
    thana: "Tongibari",
    mother_Name: "Mariam Begum ",
    district: "Munshigonj",
    name: "Mohammad Muntasir Hassan ",
    current_Join_Date: "20/07/2022",
    present_Address: "15, Kakrail ",
  },
  {
    designation_name: "Assistant Professor",
    father_Name: "Mr. A.K.M. Asaduzzaman",
    official_ID: "T201431025",
    current_Designation_ID: "A0012",
    department_ID: "000107",
    employment_Status: "Probation",
    date_of_birth: "1985-12-06 00:00:00.0",
    system_ID: "22083",
    sex: "M",
    marital_Status: "Married",
    account_No: "34189785",
    religion: "Islam",
    thana: "Rajpara",
    mother_Name: "Mrs. Rozy Zaman",
    district: "Rajshahi-6000",
    name: "Mr. Mohammad Imam Hasan Bin Asad",
    current_Join_Date: "31/07/2016",
    present_Address: "House No. 497, Road No. 15, D.O.H.S, Mirpur, Dhaka",
  },
  {
    designation_name: "Lecturer",
    father_Name: "Mr. Md. Nazrul Islam",
    official_ID: "T201131022",
    current_Designation_ID: "A0013",
    department_ID: "000107",
    employment_Status: "Temporary",
    date_of_birth: "1988-11-13 00:00:00.0",
    system_ID: "21733",
    sex: "M",
    increment_Heldup: "0",
    marital_Status: "Married",
    account_No: "34229459",
    religion: "Islam",
    thana: "Kalabagan",
    mother_Name: "Mrs. Afroza Begum",
    district: "Dhaka",
    name: "Miss Nazifah Islam",
    current_Join_Date: "23/03/2011",
    present_Address: "Flat no A4, Ena Endear, 93 Bashiruddin Road, ",
  },
  {
    designation_name: "Lecturer",
    father_Name: "Dr. S.M. Nazrul Islam",
    official_ID: "T201031021",
    current_Designation_ID: "A0013",
    department_ID: "000107",
    employment_Status: "Ad-hoc",
    date_of_birth: "1986-06-26 00:00:00.0",
    system_ID: "21692",
    sex: "M",
    increment_Heldup: "0",
    marital_Status: "Single",
    email_Address: "naeem@iict.buet.ac.bd",
    account_No: "34205328",
    religion: "Islam",
    mother_Name: "Mrs. Mahmuda Khatun",
    name: "Mr. S.M. Naeemul Islam",
    current_Join_Date: "26/10/2010",
    present_Address: "48/7B BUET Teachers Quarter, BUET, Dhaka",
  },
  {
    designation_name: "Lecturer",
    father_Name: "Md Abdur Rahman",
    official_ID: "T202331030",
    current_Designation_ID: "A0013",
    department_ID: "000107",
    employment_Status: "Temporary",
    date_of_birth: "1997-12-28 00:00:00.0",
    system_ID: "23097",
    sex: "M",
    marital_Status: "Single",
    email_Address: "saminrk@iict.buet.ac.bd",
    religion: "Islam",
    thana: "Dakshinkhan",
    mother_Name: "Mst. Anjumanara",
    district: "Dhaka",
    name: "Samin Rahman Khan",
    current_Join_Date: "30/04/2023",
    blood_Group: "A+",
    present_Address: "149/3, Holan, Dakshinkhan, Dhaka-1230",
  }
];


module.exports = { personListShort, personListLong };